-- MySQL Script generated by MySQL Workbench
-- Tue Jul  5 10:13:59 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema giveday_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema giveday_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `giveday_db` DEFAULT CHARACTER SET utf8 ;
USE `giveday_db` ;

-- -----------------------------------------------------
-- Table `giveday_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `giveday_db`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `prenom` VARCHAR(255) NOT NULL,
  `nom` VARCHAR(255) NOT NULL,
  `email` VARCHAR(180) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `giveday_db`.`cadeau`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `giveday_db`.`cadeau` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(255) NOT NULL,
  `url_site` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `giveday_db`.`cagnotte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `giveday_db`.`cagnotte` (
  `id` INT NOT NULL,
  `somme_don` FLOAT NOT NULL,
  `somme_cadeau` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `giveday_db`.`asso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `giveday_db`.`asso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `image` VARCHAR(255) NOT NULL,
  `logo` VARCHAR(255) NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_asso_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_asso_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `giveday_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `giveday_db`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `giveday_db`.`event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NULL DEFAULT NULL,
  `age` INT NULL DEFAULT NULL,
  `date` VARCHAR(40) NULL DEFAULT NULL,
  `heure_de_debut` VARCHAR(45) NULL DEFAULT NULL,
  `heure_de_fin` VARCHAR(45) NULL DEFAULT NULL,
  `lieu` VARCHAR(255) NULL DEFAULT NULL,
  `telephone` VARCHAR(45) NULL DEFAULT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `cadeau_id` INT NOT NULL,
  `cagnotte_id` INT NOT NULL,
  `asso_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE,
  INDEX `fk_event_cadeau1_idx` (`cadeau_id` ASC) VISIBLE,
  INDEX `fk_event_cagnotte1_idx` (`cagnotte_id` ASC) VISIBLE,
  INDEX `fk_event_asso1_idx` (`asso_id` ASC) VISIBLE,
  INDEX `fk_event_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_event_cadeau1`
    FOREIGN KEY (`cadeau_id`)
    REFERENCES `giveday_db`.`cadeau` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_cagnotte1`
    FOREIGN KEY (`cagnotte_id`)
    REFERENCES `giveday_db`.`cagnotte` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_asso1`
    FOREIGN KEY (`asso_id`)
    REFERENCES `giveday_db`.`asso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `giveday_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `giveday_db`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `giveday_db`.`article` (
  `id` INT NOT NULL,
  `titre` VARCHAR(255) NOT NULL,
  `date` DATE NOT NULL,
  `texte` LONGTEXT NOT NULL,
  `image` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `giveday_db`.`user_has_article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `giveday_db`.`user_has_article` (
  `user_id` INT NOT NULL,
  `article_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `article_id`),
  INDEX `fk_user_has_article_article1_idx` (`article_id` ASC) VISIBLE,
  INDEX `fk_user_has_article_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_article_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `giveday_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_article_article1`
    FOREIGN KEY (`article_id`)
    REFERENCES `giveday_db`.`article` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `giveday_db`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `giveday_db`.`tag` (
  `id` INT NOT NULL,
  `tag` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `giveday_db`.`article_has_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `giveday_db`.`article_has_tag` (
  `article_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`article_id`, `tag_id`),
  INDEX `fk_article_has_tag_tag1_idx` (`tag_id` ASC) VISIBLE,
  INDEX `fk_article_has_tag_article1_idx` (`article_id` ASC) VISIBLE,
  CONSTRAINT `fk_article_has_tag_article1`
    FOREIGN KEY (`article_id`)
    REFERENCES `giveday_db`.`article` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_has_tag_tag1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `giveday_db`.`tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
